# Importing Packages

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
from zipfile import ZipFile
!pip install pytrends
from pytrends.request import TrendReq
from pytrends import dailydata
import json
# -*- coding: utf-8 -*-

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Requirement already satisfied: pytrends in /usr/local/lib/python3.7/dist-packages (4.8.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from pytrends) (4.2.6)
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python3.7/dist-packages (from pytrends) (2.23.0)
Requirement already satisfied: pandas>=0.25 in /usr/local/lib/python3.7/dist-packages (from pytrends) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25->pytrends) (2018.9)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25->pytrends) (1.21.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25->pytrends) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25->pytrends) (1.15.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.0->pytrends) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.0->pytrends) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.0->pytrends) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.0->pytrends) (2021.10.8)

# Number of brand mentioning posts

## Brand Mentioning Posts (JSON 1 and 2)

In [ ]:
from collections import Counter

influencers = pd.read_csv('drive/Shareddrives/capstone_prayap_nithyara/influencers_data.csv')
influencers_usernames =list(influencers['Account ID'])
cou = Counter()

In [ ]:
joined_post_json_1 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_1.csv')

In [ ]:
joined_post_json_1

,Unnamed: 0,Post ID,Account ID,Sponsorship Label,JSON File,Image Files,File ID,File Contents
0,0,5,alisasia,0,1343284435982033594.json,['1343284435982033594.jpg'],1343284435982033594.json,"{'__typename': 'GraphImage', 'comments_disable..."
1,1,7,alisasia,0,1344089538574023424.json,['1344089538574023424.jpg'],1344089538574023424.json,"{'__typename': 'GraphImage', 'comments_disable..."
2,2,15,alisasia,0,1456845610208901740.json,['1456845610208901740.jpg'],1456845610208901740.json,"{'__typename': 'GraphImage', 'comments_disable..."
3,3,17,alisasia,1,1476490497539529413.json,['1476490497539529413.jpg'],1476490497539529413.json,"{'__typename': 'GraphImage', 'comments_disable..."
4,4,33,alisasia,0,1709925417879498967.json,['1709925417879498967.jpg'],1709925417879498967.json,"{'__typename': 'GraphImage', 'comments_disable..."
...,...,...,...,...,...,...,...,...
249990,249990,1601052,weartoeatiff,0,1821838873544579445.json,['1821838873544579445.jpg'],1821838873544579445.json,"{'__typename': 'GraphImage', 'comments_disable..."
249991,249991,1601053,weartoeatiff,0,1821872008697056869.json,"['1821871732391550780.jpg', '18218717343628886...",1821872008697056869.json,"{'__typename': 'GraphSidecar', 'caption_is_edi..."
249992,249992,1601056,weartoeatiff,0,1842749073742794748.json,['1842749073742794748.jpg'],1842749073742794748.json,"{'__typename': 'GraphImage', 'comments_disable..."
249993,249993,1601058,weartoeatiff,0,1861559484193446770.json,"['1861556730237088481.jpg', '18615567467961950...",1861559484193446770.json,"{'__typename': 'GraphSidecar', 'caption_is_edi..."
249994,249994,1601071,weartoeatiff,0,1981902699290795070.json,['1981902699290795070.jpg'],1981902699290795070.json,"{'__typename': 'GraphImage', 'comments_disable..."

In [ ]:
pivot = joined_post_json_1.pivot_table(index=['Account ID'], values='File ID', aggfunc='count').reset_index()

In [ ]:
pivot

               Account ID  File ID
0           00_rocketgirl        6
1         00s_supermodels        1
2                  0720_b        2
3                  0hkris        4
4                 0ldisme       19
...                   ...      ...
32185          zweigyossi        4
32186  zweiworteeinfinger        3
32187           zwhite216        1
32188         zy.interior        4
32189          zyndl_lala        1

[32190 rows x 2 columns]

In [ ]:
joined_post_json_2 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_2.csv')
pivot_2 = joined_post_json_2.pivot_table(index=['Account ID'], values='File ID', aggfunc='count').reset_index()
pivot_2

               Account ID  File ID
0           00_rocketgirl        9
1         00s_supermodels        2
2                  0720_b        2
3                  0hkris        7
4                 0ldisme       25
...                   ...      ...
32189  zweiworteeinfinger        3
32190           zwhite216        1
32191           zwithlove        1
32192         zy.interior        2
32193          zyndl_lala        1

[32194 rows x 2 columns]

In [ ]:
brand_mentions_by_influencer_1 = pivot.merge(pivot_2, how='left', left_on='Account ID', right_on='Account ID')
brand_mentions_by_influencer_1['Brand Mentioning Posts'] = brand_mentions_by_influencer_1['File ID_x'] + brand_mentions_by_influencer_1['File ID_y']
brand_mentions_by_influencer_1 = brand_mentions_by_influencer_1.drop(['File ID_x', 'File ID_y'], axis=1)
brand_mentions_by_influencer_1.to_csv('drive/Shareddrives/capstone_prayap_nithyara/brand_mentions_by_influencer_1.csv')

## Brand Mentioning Posts (JSON 3 and 4)

In [ ]:
from collections import Counter

influencers = pd.read_csv('drive/Shareddrives/capstone_prayap_nithyara/influencers_data.csv')
influencers_usernames =list(influencers['Account ID'])

In [ ]:
joined_post_json_3 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_3.csv')
pivot = joined_post_json_3.pivot_table(index=['Account ID'], values='File ID', aggfunc='count').reset_index()
joined_post_json_4 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_4.csv')
pivot_2 = joined_post_json_4.pivot_table(index=['Account ID'], values='File ID', aggfunc='count').reset_index()

In [ ]:
brand_mentions_by_influencer_2 = pivot.merge(pivot_2, how='left', left_on='Account ID', right_on='Account ID')
brand_mentions_by_influencer_2['Brand Mentioning Posts'] = brand_mentions_by_influencer_2['File ID_x'] + brand_mentions_by_influencer_2['File ID_y']
brand_mentions_by_influencer_2 = brand_mentions_by_influencer_2.drop(['File ID_x', 'File ID_y'], axis=1)
brand_mentions_by_influencer_2.to_csv('drive/Shareddrives/capstone_prayap_nithyara/brand_mentions_by_influencer_2.csv')

## Brand Mentioning Posts (JSON 5)

In [ ]:
from collections import Counter

influencers = pd.read_csv('drive/Shareddrives/capstone_prayap_nithyara/influencers_data.csv')
influencers_usernames =list(influencers['Account ID'])

In [ ]:
joined_post_json_5 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_5.csv')
pivot = joined_post_json_5.pivot_table(index=['Account ID'], values='File ID', aggfunc='count').reset_index()

In [ ]:
brand_mentions_by_influencer_3 = pivot
brand_mentions_by_influencer_3['Brand Mentioning Posts'] = brand_mentions_by_influencer_3['File ID']
brand_mentions_by_influencer_3 = brand_mentions_by_influencer_3.drop(['File ID'], axis=1)
brand_mentions_by_influencer_3.to_csv('drive/Shareddrives/capstone_prayap_nithyara/brand_mentions_by_influencer_3.csv')

## Brand Mentioning Posts (JSON 6)

In [ ]:
from collections import Counter

influencers = pd.read_csv('drive/Shareddrives/capstone_prayap_nithyara/influencers_data.csv')
influencers_usernames =list(influencers['Account ID'])

In [ ]:
joined_post_json_6 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_6.csv')
pivot = joined_post_json_6.pivot_table(index=['Account ID'], values='File ID', aggfunc='count').reset_index()

In [ ]:
brand_mentions_by_influencer_4 = pivot
brand_mentions_by_influencer_4['Brand Mentioning Posts'] = brand_mentions_by_influencer_4['File ID']
brand_mentions_by_influencer_4 = brand_mentions_by_influencer_4.drop(['File ID'], axis=1)
brand_mentions_by_influencer_4.to_csv('drive/Shareddrives/capstone_prayap_nithyara/brand_mentions_by_influencer_4.csv')

## Join Counters and Create Consolidated CSV

In [ ]:
brand_mentions_by_influencer_1 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'brand_mentions_by_influencer_1.csv')
brand_mentions_by_influencer_2 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'brand_mentions_by_influencer_2.csv')
brand_mentions_by_influencer_3 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'brand_mentions_by_influencer_3.csv')
brand_mentions_by_influencer_4 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'brand_mentions_by_influencer_4.csv')

In [ ]:
brand_mentions_by_influencer_4

       Unnamed: 0          Account ID  Brand Mentioning Posts
0               0       00_rocketgirl                       7
1               1     00s_supermodels                       3
2               2              0720_b                       2
3               3              0hkris                      12
4               4             0ldisme                      22
...           ...                 ...                     ...
33862       33862  zweiworteeinfinger                       4
33863       33863           zwhite216                       1
33864       33864           zwithlove                       1
33865       33865         zy.interior                       5
33866       33866          zyndl_lala                       1

[33867 rows x 3 columns]

In [ ]:
brand_mentions_by_influencer_combined = pd.concat([brand_mentions_by_influencer_1, brand_mentions_by_influencer_2, brand_mentions_by_influencer_3, brand_mentions_by_influencer_4]).groupby(['Account ID']).sum().reset_index()
influencers = pd.read_csv('drive/Shareddrives/capstone_prayap_nithyara/influencers_data.csv')
influencers_usernames =list(influencers['Account ID'])
brand_mentions_by_influencer_combined = brand_mentions_by_influencer_combined[brand_mentions_by_influencer_combined['Account ID'].isin(influencers_usernames)]
brand_mentions_by_influencer_combined = brand_mentions_by_influencer_combined.drop(['Unnamed: 0'], axis=1)
brand_mentions_by_influencer_combined
brand_mentions_by_influencer_combined.to_csv('drive/Shareddrives/capstone_prayap_nithyara/brand_mentions_by_influencer_combined.csv')

In [ ]:
brand_mentions_by_influencer_merge = pd.read_csv('drive/Shareddrives/capstone_prayap_nithyara/brand_mentions_by_influencer_combined.csv')
brand_mentions_by_influencer_merge = influencers.merge(brand_mentions_by_influencer_merge, how='left', left_on='Account ID', right_on='Account ID')
brand_mentions_by_influencer_merge = brand_mentions_by_influencer_merge.rename(columns={'count': 'Influencers Mentioning Brand'})
brand_mentions_by_influencer_merge = brand_mentions_by_influencer_merge.drop(['Unnamed: 0_y', 'Unnamed: 0_x'], axis=1)
brand_mentions_by_influencer_merge

,Account ID,Name,Followers,Followees,Posts,URL,T/F,Category,Bio,E-mail,Phone,Profile pic,Brand Mentioning Posts
0,fodmap_friendly_eating,FODMAP Friendly Eating,11299.0,2609.0,549.0,https://fodmapfriendlyeating.wordpress.com/,True,Creators & Celebrities,Delicious FODMAP Friendly recipes from @antoni...,tonidaroza@hotmail.co.uk,NaN,https://scontent-lax3-1.cdninstagram.com/vp/e4...,11.0
1,paileaa,paige leanne,12615.0,1207.0,1386.0,https://paileaa.com/2018/10/08/that-last-bit-o...,True,Creators & Celebrities,London | positive vibes & good times p.goodes...,p.goodes@hotmail.co.uk,NaN,https://scontent-lax3-1.cdninstagram.com/vp/b4...,65.0
2,a12team,A12 Team,1319.0,861.0,405.0,http://www.a12.com.pl/,True,Food & Personal Goods,Photography & Production services \xf0\x9f\x9...,info@a12.com.pl,4.850997e+10,https://scontent-lax3-1.cdninstagram.com/vp/f7...,10.0
3,ilbulgaro89,Andrea Paesetti,1547.0,909.0,1250.0,http://youtube.com/c/SpazioiTechItalia,True,Creators & Celebrities,Italian -- #Technology addicted -- Editor & Re...,andrea.paesetti@outlook.com,NaN,https://scontent-lax3-1.cdninstagram.com/vp/da...,1.0
4,joililikoi,Joie Lee Ruggiero,7427.0,1836.0,908.0,http://wearehaumea.com/retreats,False,NaN,HI / LA | I seek to inspire and be inspired ...,NaN,NaN,https://scontent-lax3-1.cdninstagram.com/vp/c1...,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38108,elena_280614,Elena,41870.0,1430.0,1058.0,NaN,True,Creators & Celebrities,I'm just a 17 y/o italian self-taught artist. ...,destefanoelena@outlook.it,NaN,https://scontent-lax3-1.cdninstagram.com/vp/16...,133.0
38109,carolefua,C A R O L E \xf0\x9f\x91\x91,11872.0,683.0,125.0,https://m.facebook.com/Makeupbycarolefua/,True,Creators & Celebrities,\xf0\x9f\x87\xb5\xf0\x9f\x87\xad / MUA / \xf0\...,carolefua19@gmail.com,NaN,https://scontent-lax3-1.cdninstagram.com/vp/a9...,40.0
38110,castyworld,Roberto Sikora,5645.0,800.0,389.0,https://youtu.be/6qGKCO1JOIE,True,General Interest,Discovering & Learning\xe2\x9a\xa1\xef\xb8\x8f...,castyworld@outlook.com,NaN,https://scontent-lax3-1.cdninstagram.com/vp/bd...,13.0
38111,urbaine_city,Urbaine City,1323.0,901.0,932.0,https://urbainecity.com/mtlatable-restaurants-...,True,Publishers,"Blogueuse & r\xc3\xa9dactrice pigiste, consult...",marie@urbainecity.com,NaN,https://scontent-lax3-1.cdninstagram.com/vp/b8...,32.0
38112,foodwithcarmen,C A R M E N \xf0\x9f\x8c\xbf,40557.0,317.0,537.0,http://theveganadventurer.com/,True,Creators & Celebrities,IU alum | US army compassionate living | adve...,foodwithcarmen@gmail.com,NaN,https://scontent-lax3-1.cdninstagram.com/vp/d6...,48.0

In [ ]:
brand_mentions_by_influencer_merge.to_csv('drive/Shareddrives/capstone_prayap_nithyara/brand_mentions_by_influencer_merge.csv')

# Number of sponsored brand mentioning posts

## Sponsored Brand Mentioning Posts (JSON 1 and 2)

In [ ]:
joined_post_json_1 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_1.csv')
joined_post_json_1_sponsor = joined_post_json_1[joined_post_json_1['Sponsorship Label'] == 1]
pivot = joined_post_json_1_sponsor.pivot_table(index=['Account ID'], values='File ID', aggfunc='count').reset_index()

joined_post_json_2 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_2.csv')
joined_post_json_2_sponsor = joined_post_json_2[joined_post_json_2['Sponsorship Label'] == 1]
pivot_2 = joined_post_json_2_sponsor.pivot_table(index=['Account ID'], values='File ID', aggfunc='count').reset_index()

In [ ]:
sponsored_brand_mentions_by_influencer_1 = pivot.merge(pivot_2, how='left', left_on='Account ID', right_on='Account ID')
sponsored_brand_mentions_by_influencer_1['Brand Mentioning Posts'] = sponsored_brand_mentions_by_influencer_1['File ID_x'] + sponsored_brand_mentions_by_influencer_1['File ID_y']
sponsored_brand_mentions_by_influencer_1 = sponsored_brand_mentions_by_influencer_1.drop(['File ID_x', 'File ID_y'], axis=1)
sponsored_brand_mentions_by_influencer_1.to_csv('drive/Shareddrives/capstone_prayap_nithyara/sponsored_brand_mentions_by_influencer_1.csv')

## Sponsored Brand Mentioning Posts (JSON 3 and 4)

In [ ]:
joined_post_json_3 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_3.csv')
joined_post_json_3_sponsor = joined_post_json_3[joined_post_json_3['Sponsorship Label'] == 1]
pivot = joined_post_json_3_sponsor.pivot_table(index=['Account ID'], values='File ID', aggfunc='count').reset_index()

joined_post_json_4 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_4.csv')
joined_post_json_4_sponsor = joined_post_json_4[joined_post_json_4['Sponsorship Label'] == 1]
pivot_2 = joined_post_json_4_sponsor.pivot_table(index=['Account ID'], values='File ID', aggfunc='count').reset_index()

In [ ]:
sponsored_brand_mentions_by_influencer_2 = pivot.merge(pivot_2, how='left', left_on='Account ID', right_on='Account ID')
sponsored_brand_mentions_by_influencer_2['Brand Mentioning Posts'] = sponsored_brand_mentions_by_influencer_2['File ID_x'] + sponsored_brand_mentions_by_influencer_2['File ID_y']
sponsored_brand_mentions_by_influencer_2 = sponsored_brand_mentions_by_influencer_2.drop(['File ID_x', 'File ID_y'], axis=1)
sponsored_brand_mentions_by_influencer_2.to_csv('drive/Shareddrives/capstone_prayap_nithyara/sponsored_brand_mentions_by_influencer_2.csv')

## Sponsored Brand Mentioning Posts (JSON 5)

In [ ]:
joined_post_json_5 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_5.csv')
joined_post_json_5_sponsor = joined_post_json_5[joined_post_json_5['Sponsorship Label'] == 1]
pivot = joined_post_json_5_sponsor.pivot_table(index=['Account ID'], values='File ID', aggfunc='count').reset_index()

In [ ]:
sponsored_brand_mentions_by_influencer_3 = pivot
sponsored_brand_mentions_by_influencer_3['Brand Mentioning Posts'] = sponsored_brand_mentions_by_influencer_3['File ID'] 
sponsored_brand_mentions_by_influencer_3 = sponsored_brand_mentions_by_influencer_3.drop(['File ID'], axis=1)
sponsored_brand_mentions_by_influencer_3.to_csv('drive/Shareddrives/capstone_prayap_nithyara/sponsored_brand_mentions_by_influencer_3.csv')

## Sponsored Brand Mentioning Posts (JSON 6)

In [ ]:
joined_post_json_6 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_6.csv')
joined_post_json_6_sponsor = joined_post_json_6[joined_post_json_6['Sponsorship Label'] == 1]
pivot = joined_post_json_6_sponsor.pivot_table(index=['Account ID'], values='File ID', aggfunc='count').reset_index()

In [ ]:
sponsored_brand_mentions_by_influencer_4 = pivot
sponsored_brand_mentions_by_influencer_4['Brand Mentioning Posts'] = sponsored_brand_mentions_by_influencer_4['File ID'] 
sponsored_brand_mentions_by_influencer_4 = sponsored_brand_mentions_by_influencer_4.drop(['File ID'], axis=1)
sponsored_brand_mentions_by_influencer_4.to_csv('drive/Shareddrives/capstone_prayap_nithyara/sponsored_brand_mentions_by_influencer_4.csv')

## Join Counters and Create Consolidated CSV

In [ ]:
sponsored_brand_mentions_by_influencer_1 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'sponsored_brand_mentions_by_influencer_1.csv')
sponsored_brand_mentions_by_influencer_2 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'sponsored_brand_mentions_by_influencer_2.csv')
sponsored_brand_mentions_by_influencer_3 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'sponsored_brand_mentions_by_influencer_3.csv')
sponsored_brand_mentions_by_influencer_4 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'sponsored_brand_mentions_by_influencer_4.csv')

In [ ]:
sponsored_brand_mentions_by_influencer_combined = pd.concat([sponsored_brand_mentions_by_influencer_1, sponsored_brand_mentions_by_influencer_2, sponsored_brand_mentions_by_influencer_3, sponsored_brand_mentions_by_influencer_4]).groupby(['Account ID']).sum().reset_index()
influencers = pd.read_csv('drive/Shareddrives/capstone_prayap_nithyara/influencers_data.csv')
influencers_usernames =list(influencers['Account ID'])
sponsored_brand_mentions_by_influencer_combined = sponsored_brand_mentions_by_influencer_combined[sponsored_brand_mentions_by_influencer_combined['Account ID'].isin(influencers_usernames)]
sponsored_brand_mentions_by_influencer_combined = sponsored_brand_mentions_by_influencer_combined.drop(['Unnamed: 0'], axis=1)
sponsored_brand_mentions_by_influencer_combined = sponsored_brand_mentions_by_influencer_combined.rename(columns={'Brand Mentioning Posts': 'Sponsored Brand Mentioning Posts'})
sponsored_brand_mentions_by_influencer_combined.to_csv('drive/Shareddrives/capstone_prayap_nithyara/sponsored_brand_mentions_by_influencer_combined.csv')

In [ ]:
sponsored_brand_mentions_by_influencer_merge = pd.read_csv('drive/Shareddrives/capstone_prayap_nithyara/brand_mentions_by_influencer_merge.csv')
sponsored_brand_mentions_by_influencer_merge = sponsored_brand_mentions_by_influencer_merge.merge(sponsored_brand_mentions_by_influencer_combined, how='left', left_on='Account ID', right_on='Account ID')
sponsored_brand_mentions_by_influencer_merge = sponsored_brand_mentions_by_influencer_merge.drop(['Unnamed: 0'], axis=1)
sponsored_brand_mentions_by_influencer_merge

,Account ID,Name,Followers,Followees,Posts,URL,T/F,Category,Bio,E-mail,Phone,Profile pic,Brand Mentioning Posts,Sponsored Brand Mentioning Posts
0,fodmap_friendly_eating,FODMAP Friendly Eating,11299.0,2609.0,549.0,https://fodmapfriendlyeating.wordpress.com/,True,Creators & Celebrities,Delicious FODMAP Friendly recipes from @antoni...,tonidaroza@hotmail.co.uk,NaN,https://scontent-lax3-1.cdninstagram.com/vp/e4...,11.0,3.0
1,paileaa,paige leanne,12615.0,1207.0,1386.0,https://paileaa.com/2018/10/08/that-last-bit-o...,True,Creators & Celebrities,London | positive vibes & good times p.goodes...,p.goodes@hotmail.co.uk,NaN,https://scontent-lax3-1.cdninstagram.com/vp/b4...,65.0,5.0
2,a12team,A12 Team,1319.0,861.0,405.0,http://www.a12.com.pl/,True,Food & Personal Goods,Photography & Production services \xf0\x9f\x9...,info@a12.com.pl,4.850997e+10,https://scontent-lax3-1.cdninstagram.com/vp/f7...,10.0,NaN
3,ilbulgaro89,Andrea Paesetti,1547.0,909.0,1250.0,http://youtube.com/c/SpazioiTechItalia,True,Creators & Celebrities,Italian -- #Technology addicted -- Editor & Re...,andrea.paesetti@outlook.com,NaN,https://scontent-lax3-1.cdninstagram.com/vp/da...,1.0,1.0
4,joililikoi,Joie Lee Ruggiero,7427.0,1836.0,908.0,http://wearehaumea.com/retreats,False,NaN,HI / LA | I seek to inspire and be inspired ...,NaN,NaN,https://scontent-lax3-1.cdninstagram.com/vp/c1...,12.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38108,elena_280614,Elena,41870.0,1430.0,1058.0,NaN,True,Creators & Celebrities,I'm just a 17 y/o italian self-taught artist. ...,destefanoelena@outlook.it,NaN,https://scontent-lax3-1.cdninstagram.com/vp/16...,133.0,2.0
38109,carolefua,C A R O L E \xf0\x9f\x91\x91,11872.0,683.0,125.0,https://m.facebook.com/Makeupbycarolefua/,True,Creators & Celebrities,\xf0\x9f\x87\xb5\xf0\x9f\x87\xad / MUA / \xf0\...,carolefua19@gmail.com,NaN,https://scontent-lax3-1.cdninstagram.com/vp/a9...,40.0,3.0
38110,castyworld,Roberto Sikora,5645.0,800.0,389.0,https://youtu.be/6qGKCO1JOIE,True,General Interest,Discovering & Learning\xe2\x9a\xa1\xef\xb8\x8f...,castyworld@outlook.com,NaN,https://scontent-lax3-1.cdninstagram.com/vp/bd...,13.0,NaN
38111,urbaine_city,Urbaine City,1323.0,901.0,932.0,https://urbainecity.com/mtlatable-restaurants-...,True,Publishers,"Blogueuse & r\xc3\xa9dactrice pigiste, consult...",marie@urbainecity.com,NaN,https://scontent-lax3-1.cdninstagram.com/vp/b8...,32.0,0.0
38112,foodwithcarmen,C A R M E N \xf0\x9f\x8c\xbf,40557.0,317.0,537.0,http://theveganadventurer.com/,True,Creators & Celebrities,IU alum | US army compassionate living | adve...,foodwithcarmen@gmail.com,NaN,https://scontent-lax3-1.cdninstagram.com/vp/d6...,48.0,5.0

In [ ]:
sponsored_brand_mentions_by_influencer_merge.to_csv('drive/Shareddrives/capstone_prayap_nithyara/sponsored_brand_mentions_by_influencer_merge.csv')