# Import Packages

In [ ]:
#import libraries
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
from zipfile import ZipFile
import json

Mounted at /content/drive

# Data Preprocessing for Network Analysis

##JSON's DONT RUN

In [ ]:
#load list of brand usernames
brands = pd.read_csv('drive/Shareddrives/capstone_prayap_nithyara/brands_data.csv')
brand_usernames =list(brands['Account ID'])

In [ ]:
#processing json files
joined_post_json_1 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_1.csv')
joined_post_json_1 = joined_post_json_1[joined_post_json_1['Sponsorship Label'] == 1]
b = joined_post_json_1['File Contents'].str.findall(r'@[a-zA-Z0-9._]+')
account_id = joined_post_json_1['Account ID'].tolist()
flat_list = [list(set(item)) for item in b]
brand_influencer_df = pd.DataFrame(
    {'Account ID': account_id,
     'Brands': flat_list})
brand_influencer_df_edit = brand_influencer_df.explode('Brands')
brand_influencer_df_edit['Brands'] = brand_influencer_df_edit['Brands'].apply(lambda x: str(x)[1:])
merge = brand_influencer_df_edit.merge(brands[['Account ID', 'Category']], how='left', left_on='Brands', right_on='Account ID')
merge[['Category']] = merge[['Category']].fillna('Other')
merge[['Category']] = merge[['Category']].replace('', 'Other')
merge = merge.dropna()
merge = merge.drop(['Account ID_y'], axis=1)
merge = merge.rename({'Category': 'Brand Category', 'Brands': 'Brand', 'Account ID_x': 'Influencer'}, axis=1)
merge1 = merge.drop_duplicates()

In [ ]:
joined_post_json_2 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_2.csv')
joined_post_json_2 = joined_post_json_2[joined_post_json_2['Sponsorship Label'] == 1]
b = joined_post_json_2['File Contents'].str.findall(r'@[a-zA-Z0-9._]+')
account_id = joined_post_json_2['Account ID'].tolist()
flat_list = [list(set(item)) for item in b]
brand_influencer_df = pd.DataFrame(
    {'Account ID': account_id,
     'Brands': flat_list})
brand_influencer_df_edit = brand_influencer_df.explode('Brands')
brand_influencer_df_edit['Brands'] = brand_influencer_df_edit['Brands'].apply(lambda x: str(x)[1:])
merge = brand_influencer_df_edit.merge(brands[['Account ID', 'Category']], how='left', left_on='Brands', right_on='Account ID')
merge[['Category']] = merge[['Category']].fillna('Other')
merge[['Category']] = merge[['Category']].replace('', 'Other')
merge = merge.dropna()
merge = merge.drop(['Account ID_y'], axis=1)
merge = merge.rename({'Category': 'Brand Category', 'Brands': 'Brand', 'Account ID_x': 'Influencer'}, axis=1)
merge2 = merge.drop_duplicates()

In [ ]:
joined_post_json_3 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_3.csv')
joined_post_json_3 = joined_post_json_3[joined_post_json_3['Sponsorship Label'] == 1]
b = joined_post_json_3['File Contents'].str.findall(r'@[a-zA-Z0-9._]+')
account_id = joined_post_json_3['Account ID'].tolist()
flat_list = [list(set(item)) for item in b]
brand_influencer_df = pd.DataFrame(
    {'Account ID': account_id,
     'Brands': flat_list})
brand_influencer_df_edit = brand_influencer_df.explode('Brands')
brand_influencer_df_edit['Brands'] = brand_influencer_df_edit['Brands'].apply(lambda x: str(x)[1:])
merge = brand_influencer_df_edit.merge(brands[['Account ID', 'Category']], how='left', left_on='Brands', right_on='Account ID')
merge[['Category']] = merge[['Category']].fillna('Other')
merge[['Category']] = merge[['Category']].replace('', 'Other')
merge = merge.dropna()
merge = merge.drop(['Account ID_y'], axis=1)
merge = merge.rename({'Category': 'Brand Category', 'Brands': 'Brand', 'Account ID_x': 'Influencer'}, axis=1)
merge3 = merge.drop_duplicates()

In [ ]:
joined_post_json_4 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_4.csv')
joined_post_json_4 = joined_post_json_4[joined_post_json_4['Sponsorship Label'] == 1]
b = joined_post_json_4['File Contents'].str.findall(r'@[a-zA-Z0-9._]+')
account_id = joined_post_json_4['Account ID'].tolist()
flat_list = [list(set(item)) for item in b]
brand_influencer_df = pd.DataFrame(
    {'Account ID': account_id,
     'Brands': flat_list})
brand_influencer_df_edit = brand_influencer_df.explode('Brands')
brand_influencer_df_edit['Brands'] = brand_influencer_df_edit['Brands'].apply(lambda x: str(x)[1:])
merge = brand_influencer_df_edit.merge(brands[['Account ID', 'Category']], how='left', left_on='Brands', right_on='Account ID')
merge[['Category']] = merge[['Category']].fillna('Other')
merge[['Category']] = merge[['Category']].replace('', 'Other')
merge = merge.dropna()
merge = merge.drop(['Account ID_y'], axis=1)
merge = merge.rename({'Category': 'Brand Category', 'Brands': 'Brand', 'Account ID_x': 'Influencer'}, axis=1)
merge4 = merge.drop_duplicates()

In [ ]:
joined_post_json_5 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_5.csv')
joined_post_json_5 = joined_post_json_5[joined_post_json_5['Sponsorship Label'] == 1]
b = joined_post_json_5['File Contents'].str.findall(r'@[a-zA-Z0-9._]+')
account_id = joined_post_json_5['Account ID'].tolist()
flat_list = [list(set(item)) for item in b]
brand_influencer_df = pd.DataFrame(
    {'Account ID': account_id,
     'Brands': flat_list})
brand_influencer_df_edit = brand_influencer_df.explode('Brands')
brand_influencer_df_edit['Brands'] = brand_influencer_df_edit['Brands'].apply(lambda x: str(x)[1:])
merge = brand_influencer_df_edit.merge(brands[['Account ID', 'Category']], how='left', left_on='Brands', right_on='Account ID')
merge[['Category']] = merge[['Category']].fillna('Other')
merge[['Category']] = merge[['Category']].replace('', 'Other')
merge = merge.dropna()
merge = merge.drop(['Account ID_y'], axis=1)
merge = merge.rename({'Category': 'Brand Category', 'Brands': 'Brand', 'Account ID_x': 'Influencer'}, axis=1)
merge5 = merge.drop_duplicates()

In [ ]:
joined_post_json_6 = pd.read_csv("drive/Shareddrives/capstone_prayap_nithyara/" + 'joined_post_json_6.csv')
joined_post_json_6 = joined_post_json_6[joined_post_json_6['Sponsorship Label'] == 1]
b = joined_post_json_6['File Contents'].str.findall(r'@[a-zA-Z0-9._]+')
account_id = joined_post_json_6['Account ID'].tolist()
flat_list = [list(set(item)) for item in b]
brand_influencer_df = pd.DataFrame(
    {'Account ID': account_id,
     'Brands': flat_list})
brand_influencer_df_edit = brand_influencer_df.explode('Brands')
brand_influencer_df_edit['Brands'] = brand_influencer_df_edit['Brands'].apply(lambda x: str(x)[1:])
merge = brand_influencer_df_edit.merge(brands[['Account ID', 'Category']], how='left', left_on='Brands', right_on='Account ID')
merge[['Category']] = merge[['Category']].fillna('Other')
merge[['Category']] = merge[['Category']].replace('', 'Other')
merge = merge.dropna()
merge = merge.drop(['Account ID_y'], axis=1)
merge = merge.rename({'Category': 'Brand Category', 'Brands': 'Brand', 'Account ID_x': 'Influencer'}, axis=1)
merge6 = merge.drop_duplicates()

In [ ]:
merge = pd.concat([merge1,merge2,merge3,merge4,merge5,merge6]).reset_index()

In [ ]:
#merge = merge.drop(['index', 'Unnamed: 0'], axis=1)

In [ ]:
merge.head()

,index,Influencer,Brand,Brand Category
0,0,alisasia,kraft_macandcheese,Personal Goods & General Merchandise Stores
1,1,about_yvi,socosi_jewelry,Personal Goods & General Merchandise Stores
2,2,alinatsvor,caesarspalace,Local Events
3,11,allthingskate,livingproofinc,Personal Goods & General Merchandise Stores
4,14,allthingskate,t3micro,Personal Goods & General Merchandise Stores

In [ ]:
merge

,index,Influencer,Brand,Brand Category
0,0,alisasia,kraft_macandcheese,Personal Goods & General Merchandise Stores
1,1,about_yvi,socosi_jewelry,Personal Goods & General Merchandise Stores
2,2,alinatsvor,caesarspalace,Local Events
3,11,allthingskate,livingproofinc,Personal Goods & General Merchandise Stores
4,14,allthingskate,t3micro,Personal Goods & General Merchandise Stores
...,...,...,...,...
208366,156138,thefashionpoet,daveandbusters,Local Events
208367,156144,thefashionpoet,sephora,Personal Goods & General Merchandise Stores
208368,156154,thefashionpoet,ticketmaster,Personal Goods & General Merchandise Stores
208369,156160,thefashionpoet,eatvicecream,Grocery & Convenience Stores
208370,156161,thefashionpoet,publix,Grocery & Convenience Stores

In [ ]:
merge.to_csv( "influencer_brand_category.csv", index=False, encoding='utf-8-sig')
!cp influencer_brand_category.csv "/content/drive/Shareddrives/capstone_prayap_nithyara/models"

In [ ]:
merge[merge['Influencer']=='alisasia']

,index,Influencer,Brand,Brand Category
0,0,alisasia,kraft_macandcheese,Personal Goods & General Merchandise Stores
32752,0,alisasia,rosegal_official,Personal Goods & General Merchandise Stores
65750,0,alisasia,elfwigs,Personal Goods & General Merchandise Stores
98463,0,alisasia,grazeusa,Personal Goods & General Merchandise Stores
98464,1,alisasia,reebokclassics,Personal Goods & General Merchandise Stores
131019,0,alisasia,livingroyal,Personal Goods & General Merchandise Stores
164277,1,alisasia,footlocker,Personal Goods & General Merchandise Stores
164278,2,alisasia,reebok,Personal Goods & General Merchandise Stores